/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as ProjectsIndexImport } from './routes/projects/index'
import { Route as ProjectsCreateImport } from './routes/projects/create'
import { Route as ProjectsProjectIdIndexImport } from './routes/projects/$projectId/index'
import { Route as ProjectsProjectIdMenuSectionIndexImport } from './routes/projects/$projectId/$menuSection/index'
import { Route as ProjectsProjectIdMenuSectionMenuItemImport } from './routes/projects/$projectId/$menuSection/$menuItem'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ProjectsIndexRoute = ProjectsIndexImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRoute,
} as any)

const ProjectsCreateRoute = ProjectsCreateImport.update({
  id: '/projects/create',
  path: '/projects/create',
  getParentRoute: () => rootRoute,
} as any)

const ProjectsProjectIdIndexRoute = ProjectsProjectIdIndexImport.update({
  id: '/projects/$projectId/',
  path: '/projects/$projectId/',
  getParentRoute: () => rootRoute,
} as any)

const ProjectsProjectIdMenuSectionIndexRoute =
  ProjectsProjectIdMenuSectionIndexImport.update({
    id: '/projects/$projectId/$menuSection/',
    path: '/projects/$projectId/$menuSection/',
    getParentRoute: () => rootRoute,
  } as any)

const ProjectsProjectIdMenuSectionMenuItemRoute =
  ProjectsProjectIdMenuSectionMenuItemImport.update({
    id: '/projects/$projectId/$menuSection/$menuItem',
    path: '/projects/$projectId/$menuSection/$menuItem',
    getParentRoute: () => rootRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/projects/create': {
      id: '/projects/create'
      path: '/projects/create'
      fullPath: '/projects/create'
      preLoaderRoute: typeof ProjectsCreateImport
      parentRoute: typeof rootRoute
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsIndexImport
      parentRoute: typeof rootRoute
    }
    '/projects/$projectId/': {
      id: '/projects/$projectId/'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof ProjectsProjectIdIndexImport
      parentRoute: typeof rootRoute
    }
    '/projects/$projectId/$menuSection/$menuItem': {
      id: '/projects/$projectId/$menuSection/$menuItem'
      path: '/projects/$projectId/$menuSection/$menuItem'
      fullPath: '/projects/$projectId/$menuSection/$menuItem'
      preLoaderRoute: typeof ProjectsProjectIdMenuSectionMenuItemImport
      parentRoute: typeof rootRoute
    }
    '/projects/$projectId/$menuSection/': {
      id: '/projects/$projectId/$menuSection/'
      path: '/projects/$projectId/$menuSection'
      fullPath: '/projects/$projectId/$menuSection'
      preLoaderRoute: typeof ProjectsProjectIdMenuSectionIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/projects/create': typeof ProjectsCreateRoute
  '/projects': typeof ProjectsIndexRoute
  '/projects/$projectId': typeof ProjectsProjectIdIndexRoute
  '/projects/$projectId/$menuSection/$menuItem': typeof ProjectsProjectIdMenuSectionMenuItemRoute
  '/projects/$projectId/$menuSection': typeof ProjectsProjectIdMenuSectionIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/projects/create': typeof ProjectsCreateRoute
  '/projects': typeof ProjectsIndexRoute
  '/projects/$projectId': typeof ProjectsProjectIdIndexRoute
  '/projects/$projectId/$menuSection/$menuItem': typeof ProjectsProjectIdMenuSectionMenuItemRoute
  '/projects/$projectId/$menuSection': typeof ProjectsProjectIdMenuSectionIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/projects/create': typeof ProjectsCreateRoute
  '/projects/': typeof ProjectsIndexRoute
  '/projects/$projectId/': typeof ProjectsProjectIdIndexRoute
  '/projects/$projectId/$menuSection/$menuItem': typeof ProjectsProjectIdMenuSectionMenuItemRoute
  '/projects/$projectId/$menuSection/': typeof ProjectsProjectIdMenuSectionIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/projects/create'
    | '/projects'
    | '/projects/$projectId'
    | '/projects/$projectId/$menuSection/$menuItem'
    | '/projects/$projectId/$menuSection'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/projects/create'
    | '/projects'
    | '/projects/$projectId'
    | '/projects/$projectId/$menuSection/$menuItem'
    | '/projects/$projectId/$menuSection'
  id:
    | '__root__'
    | '/'
    | '/projects/create'
    | '/projects/'
    | '/projects/$projectId/'
    | '/projects/$projectId/$menuSection/$menuItem'
    | '/projects/$projectId/$menuSection/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProjectsCreateRoute: typeof ProjectsCreateRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
  ProjectsProjectIdIndexRoute: typeof ProjectsProjectIdIndexRoute
  ProjectsProjectIdMenuSectionMenuItemRoute: typeof ProjectsProjectIdMenuSectionMenuItemRoute
  ProjectsProjectIdMenuSectionIndexRoute: typeof ProjectsProjectIdMenuSectionIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProjectsCreateRoute: ProjectsCreateRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
  ProjectsProjectIdIndexRoute: ProjectsProjectIdIndexRoute,
  ProjectsProjectIdMenuSectionMenuItemRoute:
    ProjectsProjectIdMenuSectionMenuItemRoute,
  ProjectsProjectIdMenuSectionIndexRoute:
    ProjectsProjectIdMenuSectionIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/projects/create",
        "/projects/",
        "/projects/$projectId/",
        "/projects/$projectId/$menuSection/$menuItem",
        "/projects/$projectId/$menuSection/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/projects/create": {
      "filePath": "projects/create.tsx"
    },
    "/projects/": {
      "filePath": "projects/index.tsx"
    },
    "/projects/$projectId/": {
      "filePath": "projects/$projectId/index.tsx"
    },
    "/projects/$projectId/$menuSection/$menuItem": {
      "filePath": "projects/$projectId/$menuSection/$menuItem.tsx"
    },
    "/projects/$projectId/$menuSection/": {
      "filePath": "projects/$projectId/$menuSection/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
